-- PACK ACCESSIBILITÉ & SÉMANTIQUE
INSERT INTO challenges (titre, description, niveau, xp_reward, type, initial_code, test_keywords, language)
VALUES 
('🚀 Barre de navigation accessible', 'Crée une barre de navigation responsive avec un lien d''évitement (''skip to content'') pour améliorer l''accessibilité. Ajoute les attributs ARIA nécessaires et assure-toi que le menu est utilisable au clavier.', 'Débutant', 100, 'algo', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Nav accessible</title>\n  <style>\n    /* Ton CSS ici */\n  </style>\n</head>\n<body>\n  <!-- Ajoute le lien d''évitement et la navigation -->\n  <main id="content">\n    <h1>Contenu principal</h1>\n    <p>Utilise Tab pour naviguer.</p>\n  </main>\n</body>\n</html>', ARRAY['aria-label', 'skip-link', '#content', 'nav', 'ul', 'li'], 'HTML'),

('🖼️ Galerie d''images responsive avec figcaption', 'Construis une galerie d''images qui s''affiche en grille (3 colonnes sur desktop, 1 sur mobile). Chaque image doit avoir une légende descriptive via <figcaption>. Assure-toi que les images sont responsives (max-width:100%).', 'Débutant', 110, 'pixel_perfect', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Galerie responsive</title>\n  <style>\n    /* Ton code CSS ici */\n  </style>\n</head>\n<body>\n  <figure class="gallery">\n    <!-- Ajoute au moins 3 figures avec image et figcaption -->\n  </figure>\n</body>\n</html>', ARRAY['display: grid', 'grid-template-columns', '<figcaption>', '<figure>', 'max-width: 100%'], 'HTML'),

('📄 Article sémantique avec microdonnées', 'Rédige un article de blog structuré avec <article>, <header>, <section>. Ajoute des microdonnées Schema.org (itemscope, itemtype) pour le titre, l''auteur et la date de publication.', 'Intermédiaire', 150, 'algo', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <title>Article sémantique</title>\n</head>\n<body>\n  <!-- Construis l''article ici -->\n</body>\n</html>', ARRAY['itemscope', 'itemtype', 'itemprop="headline"', 'itemprop="author"', 'datetime', '<article>'], 'HTML'),

('📝 Formulaire accessible avec champs groupés', 'Crée un formulaire d''inscription avec groupement de champs (fieldset/legend), labels explicites, et attributs ARIA pour les messages d''erreur simulés. Le formulaire doit contenir : nom, email, préférences (radio), et un champ obligatoire avec indication.', 'Intermédiaire', 180, 'algo', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <title>Formulaire accessible</title>\n</head>\n<body>\n  <form>\n    <!-- Ajoute les champs ici -->\n  </form>\n</body>\n</html>', ARRAY['<fieldset>', '<legend>', 'aria-required', 'aria-invalid', 'aria-live', 'required'], 'HTML'),

('🎮 Contrôles personnalisés pour lecteur vidéo', 'Implémente un lecteur vidéo HTML5 avec contrôles personnalisés (play/pause, volume, progression) entièrement accessibles au clavier et avec attributs ARIA. Cache les contrôles natifs.', 'Avancé', 250, 'algo', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <title>Lecteur vidéo accessible</title>\n  <style>\n    .video-container { width: 640px; }\n    .controls { display: flex; gap: 10px; }\n  </style>\n</head>\n<body>\n  <div class="video-container">\n    <video id="video" src="https://www.w3schools.com/html/mov_bbb.mp4"></video>\n    <div class="controls" role="toolbar">\n      <button id="playPauseBtn">Play</button>\n      <input type="range" id="progress" value="0" step="0.01">\n      <input type="range" id="volume" min="0" max="1" step="0.01" value="0.5">\n    </div>\n  </div>\n  <script>\n    // Implémente la logique ici\n  </script>\n</body>\n</html>', ARRAY['video.play()', 'video.pause()', 'video.currentTime', 'video.volume', 'role="toolbar"', 'aria-label'], 'HTML'),

('📊 Tableau responsive avec défilement horizontal et en-tête fixe', 'Crée un tableau de données large (au moins 6 colonnes) qui devient défilable horizontalement sur mobile. L''en-tête doit rester visible lors du défilement vertical (position: sticky).', 'Avancé', 220, 'pixel_perfect', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Tableau responsive</title>\n  <style>\n    /* à compléter */\n  </style>\n</head>\n<body>\n  <div class="table-wrapper">\n    <table>\n      <!-- génère des données -->\n    </table>\n  </div>\n</body>\n</html>', ARRAY['overflow-x: auto', 'position: sticky', 'top: 0', 'border-collapse', 'min-width:'], 'HTML'),

('🗺️ Carte SVG interactive avec info-bulle', 'Construis une carte SVG (par exemple régions) où chaque région affiche une infobulle personnalisée (tooltip) au survol et au focus, sans JavaScript (uniquement CSS et attributs title/aria-describedby).', 'Avancé', 280, 'pixel_perfect', '<!DOCTYPE html>\n<html lang="fr">\n<head>\n  <meta charset="UTF-8">\n  <title>Carte interactive</title>\n  <style>\n    /* styles pour tooltip */\n  </style>\n</head>\n<body>\n  <svg viewBox="0 0 200 200" role="img" aria-label="Carte des régions">\n    <!-- Dessine des polygones -->\n  </svg>\n</body>\n</html>', ARRAY['<svg>', '<polygon>', 'tabindex="0"', 'aria-describedby', 'role="tooltip"', ':hover', ':focus'], 'HTML');
